version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: congrad-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: congrad
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]

  backend:
    image: congrad-backend:latest
    container_name: congrad-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/congrad?serverTimezone=Asia/Seoul&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0528
    ports:
      - "8080:8080"
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    image: congrad-frontend:latest
    container_name: congrad-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile

volumes:
  db-data:
